### ISSUE TITLE
Allow modification to prefix by server owners

### ISSUE THREAD

**Issue by elmellowyellow** [ThibautPlg/Discord-LEGO-Bot#4]
I'm a server owner with admittedly little experience with coding myself, so I might be missing something obvious, but the ! prefix is shared with several other bots including MEE6. Is it possible to add in a command to reconfigure LegBot's prefix?

**Comment by ThibautPlg** [comment]
Hi, 
Thanks for your message. 
I can't see the problem with MEE6, unless you have a custom command that overlap Legbot's. 

I have currently no plan to add such a feature, it would require to have a way to store each server wanted prefix, and so having a new service (any kind of database) to maintain, update and monitor.  I'm not closed to the idea, but I have other priorities, and adding complexity to a personal side project like LegBot is not currently on the table. :-)
