### ISSUE TITLE
Unable to search Bricklink for parts

### ISSUE THREAD

**Issue by wrtyler** [ThibautPlg/Discord-LEGO-Bot#5]
If you do a search !bl (part #)  what your code does is execute this command: https://www.bricklink.com/v2/catalog/catalogitem.page?S=  which is the command to search for a set  you need https://www.bricklink.com/v2/catalog/catalogitem.page?P=  for parts searching on Bricklink.

**Comment by ThibautPlg** [comment]
Hello,
Indeed, the command `!bl` aims to return the direct Bricklink URL regarding a set, not a part. If you want a Bricklink link concerning a part, you should use the `!part` command and click the link in the "Shop" section.

**Comment by wrtyler** [comment]
Thank you for providing working approach for getting part information from Bricklink.  It still would be nice to have a !blpart and a !blset inquiry.  Either way, your LegoBot is immensely helpful.  And thank you for closing the issue.
